[[Event]]
  EventType = 'DataLoaded'
  Commands = [
    ## These adjust level ranges for the encounter zones (Planets, Labs, Mines, Etc)
    'setgs uDefaultLevelZone01min 1',
    'setgs uDefaultLevelZone01max 15',
    'setgs uDefaultLevelZone02min 16',
    'setgs uDefaultLevelZone02max 30',
    'setgs uDefaultLevelZone03min 31',
    'setgs uDefaultLevelZone03max 75',
    'setgs uDefaultLevelZone04min 76',
    'setgs uDefaultLevelZone04max 125',
    'setgs uDefaultLevelZone05min 126',
    'setgs uDefaultLevelZone05max 175',
    'setgs uDefaultLevelZone06min 176',
    'setgs uDefaultLevelZone06max 999',
    'setgs uDefaultLevelZone07min 200',
    'setgs uDefaultLevelZone07max 999',
    'setgs uDefaultLevelZone08min 225',
    'setgs uDefaultLevelZone08max 999',
    'setgs uDefaultLevelZone09min 250',
    'setgs uDefaultLevelZone09max 999',

    ## This adjusts the level ranges between you and the mobs maybe seems to help but mixed opinion if it did anything in earlier games
    ## And in testing I did get some sawns that were 20 levels higher them me
    'setgs iLevCharLevelDifferenceMax 5',

    ##
    ## START: NEW GAME OR NGP RESET REQUIRED FOR THIS PART
    ##
    ## See https://www.creationkit.com/index.php?title=LeveledCharacter
    ##

    ## Easy: Select from all actors in the list whose level is 33% or lower than the resolved level of the space
    ## iLevelChallengeThresholdEasy:StarMap planet marker colorings with green are triggered using this 
    'setgs "iLevelChallengeThresholdEasy:StarMap" 20', # (Default 11)
    'setgs fLeveledActorMultEasy 1', ## (Default 0.4)

    ## Medium: Select the actor that is closest to 66% of the resolved level of the space without exceeding that level.
    ## iLevelChallengeThresholdAverage:StarMap planet marker colorings with blue are triggered using this 
    'setgs "iLevelChallengeThresholdAverage:StarMap" 40', # (Default 21)
    'setgs fLeveledActorMultMedium 1', ## (Default 0.7)

    ## Hard: Select the actor that is closest to the resolved level of the space without exceeding that level
    ## iLevelChallengeThresholdChallenging:StarMap planet marker colorings with yellow are triggered using this
    'setgs "iLevelChallengeThresholdChallenging:StarMap" 60', # (Default 31)
    'setgs fLeveledActorMultHard 1.10', ## (Default 1)

    ## Very Hard: Select the actor that is closest to 125% of the resolved level of the space without exceeding that level. 
    ## If this would produce the same result as the Hard difficulty creature, select the enemy one step higher, if any, regardless of its level
    ## iLevelChallengeThresholdDeadly:StarMap planet marker colorings with red are triggered using this
    'setgs "iLevelChallengeThresholdDeadly:StarMap" 70', # (Default 51 Highest System 75)
    'setgs fLeveledActorMultVeryHard 1.10', ## (Default 1.25)

    ## If player is over zones level this controls the amount of the players level used to adjust the zone. This doesn't seem to work or majorly breaks the other settings (Default 1) 
    'setgs fLevelScalingMult 1',

    ##
    ## END: NEW GAME OR NGP RESET REQUIRED
    ##

  ]